name: 🔐 Auth: GitHub + Email Login
description: Implement Netlify-style GitHub OAuth and email login/signup flow
title: "[Auth] GitHub + Email Login Implementation"
labels: [auth, backend, enhancement, good first issue]
assignees:
  - your-github-username
body:
  - type: markdown
    attributes:
      value: |
        ## 📝 Description

        Build Netlify-style authentication with dual login:
        - GitHub OAuth (via OAuth2 Authorization Code Grant)
        - Email + Password (JWT-based sessions)

  - type: checkboxes
    id: steps
    attributes:
      label: Tasks
      options:
        - label: Register GitHub OAuth app and set environment variables
        - label: Create User model (GitHub + Email support)
        - label: Create `/auth/github/callback` route
        - label: Create `/signup` and `/login` routes
        - label: Implement GitHub OAuth service + JWT issuance
        - label: Add middleware to protect private routes
        - label: (Optional) Add frontend GitHub login button

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      placeholder: Add any discussion, links, or blockers here.
